"""Validate the canonical CI skills and their generated Claude mirror.

`.agents/skills/` is authored; `.claude/skills/` is generated by
`sync_skills.py`. This check enforces the skill frontmatter contract (name
matches directory, description present, no unresolved placeholders, bounded
size), the fixed skill set, and — like a generated-docs drift check — that the
mirror is byte-identical to the source. It plugs into validate_all via
`check()`.
"""
from __future__ import annotations

import hashlib
import re
import sys
import tempfile
from pathlib import Path

from ci_workflows_tools._strict_yaml import strict_loads

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = REPO_ROOT / ".agents" / "skills"
MIRROR = REPO_ROOT / ".claude" / "skills"
NAME_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
MARKER = ".generated-from-agents-skills"
EXPECTED_SKILLS = {
    # Portable CI/GitHub-Actions doctrine (published as product).
    "ci-inventory-audit", "github-actions-authoring", "github-actions-security",
    "ci-free-tier-planner", "ci-failure-triage", "ci-release-provenance",
    "ci-cost-performance", "ci-runtime-contract-testing",
    "ci-consumer-adoption",
    # Repository-operation skill for agents working on this repo. One, not
    # three: orientation, change flow and release flow described a single
    # workflow across three files that had to be kept in step with each other
    # and with AGENTS.md, and drifted from both.
    "nddev-repo-flow",
}
PLACEHOLDERS = ("TODO_PLACEHOLDER", "<fill-me>", "TBD_PLACEHOLDER")
# Volatile plan/price/quota figures must live only in catalog/product-facts.yml
# (freshness-gated), never hard-coded in a static skill. Flag comma-grouped
# allowances (e.g. "2,000"/"50,000"), "<n> minutes", and storage-size units so
# a stale number can never masquerade as durable doctrine.
VOLATILE_QUOTA_RE = re.compile(
    r"\b\d{1,3}(?:,\d{3})+\b"
    r"|\b\d[\d,]*\s+(?:hosted\s+|included\s+)?minutes\b"
    r"|\b\d+\s?(?:MB|GB|TB)\b",
    re.IGNORECASE,
)


def _frontmatter(text: str, origin: str = "<skill>") -> dict:
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("unterminated YAML frontmatter")
    return strict_loads(text[4:end], origin) or {}


def _guard_selftest() -> list[str]:
    """Prove the volatile-quota guard flags real tariffs and not false friends."""
    problems: list[str] = []
    must_flag = ["2,000", "50,000 included minutes", "500 MB", "cache 10 GB",
                 "3,000 minutes"]
    must_pass = ["50/75/90/100 percent", "version 1.7.12", "ubuntu-latest",
                 "GB-minutes as a unit", "section 4 of 7"]
    for sample in must_flag:
        if not VOLATILE_QUOTA_RE.search(sample):
            problems.append(f"check_skills self-test: guard missed {sample!r}")
    for sample in must_pass:
        if VOLATILE_QUOTA_RE.search(sample):
            problems.append(f"check_skills self-test: guard false-positive {sample!r}")
    return problems


def _mirror_problems(source: Path, mirror: Path) -> list[str]:
    """Require an exact source tree plus the one declared generation marker."""
    problems: list[str] = []
    source_files = {
        path.relative_to(source): path
        for path in source.rglob("*") if path.is_file()
    }
    mirror_files = {
        path.relative_to(mirror): path
        for path in mirror.rglob("*") if path.is_file()
    } if mirror.is_dir() else {}
    expected = set(source_files) | {Path(MARKER)}
    if set(mirror_files) != expected:
        problems.append(
            f"mirror file inventory drift: missing={sorted(str(p) for p in expected - set(mirror_files))} "
            f"extra={sorted(str(p) for p in set(mirror_files) - expected)}"
        )
    for relative, source_path in source_files.items():
        mirror_path = mirror_files.get(relative)
        if mirror_path is not None and source_path.read_bytes() != mirror_path.read_bytes():
            problems.append(f"mirror byte drift: {relative}")
    skill = source / "SKILL.md"
    marker = mirror_files.get(Path(MARKER))
    if skill.is_file() and marker is not None:
        expected_marker = (
            f"source=.agents/skills/{source.name}/SKILL.md\n"
            f"sha256={hashlib.sha256(skill.read_bytes()).hexdigest()}\n"
        ).encode()
        if marker.read_bytes() != expected_marker:
            problems.append("mirror generation marker drift")
    return problems


def _mirror_selftest() -> list[str]:
    problems: list[str] = []
    with tempfile.TemporaryDirectory(prefix="ci-workflows-skill-mirror-") as raw:
        root = Path(raw)
        source = root / ".agents" / "skills" / "fixture"
        mirror = root / ".claude" / "skills" / "fixture"
        source.mkdir(parents=True)
        mirror.mkdir(parents=True)
        payload = b"---\nname: fixture\n---\n"
        (source / "SKILL.md").write_bytes(payload)
        (mirror / "SKILL.md").write_bytes(payload)
        (mirror / MARKER).write_text(
            "source=.agents/skills/fixture/SKILL.md\n"
            f"sha256={hashlib.sha256(payload).hexdigest()}\n",
            encoding="utf-8",
        )
        if _mirror_problems(source, mirror):
            problems.append("check_skills self-test: canonical mirror rejected")
        (mirror / "unexpected.txt").write_text("drift\n", encoding="utf-8")
        if not _mirror_problems(source, mirror):
            problems.append("check_skills self-test: unexpected generated output accepted")
        (mirror / "unexpected.txt").unlink()
        (mirror / "SKILL.md").write_text("stale\n", encoding="utf-8")
        if not _mirror_problems(source, mirror):
            problems.append("check_skills self-test: mirror byte drift accepted")
    return problems


def check() -> list[str]:
    problems: list[str] = []
    if not CANONICAL.is_dir():
        return [f"missing canonical skill directory: {CANONICAL.relative_to(REPO_ROOT)}"]

    names: list[str] = []
    for skill_dir in sorted(p for p in CANONICAL.iterdir() if p.is_dir()):
        source = skill_dir / "SKILL.md"
        where = f".agents/skills/{skill_dir.name}/SKILL.md"
        if not source.is_file():
            problems.append(f"{where}: missing SKILL.md")
            continue
        text = source.read_text(encoding="utf-8")
        try:
            meta = _frontmatter(text, str(source))
        except ValueError as exc:
            problems.append(f"{where}: {exc}")
            continue
        name = meta.get("name")
        description = meta.get("description")
        if name != skill_dir.name:
            problems.append(f"{where}: name must equal directory {skill_dir.name!r}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            problems.append(f"{where}: name must be kebab-case")
        else:
            names.append(name)
        if not isinstance(description, str) or len(description.strip()) < 40:
            problems.append(f"{where}: description must be a substantial string")
        if len(text.splitlines()) > 500:
            problems.append(f"{where}: exceeds the 500-line skill budget")
        for token in PLACEHOLDERS:
            if token in text:
                problems.append(f"{where}: unresolved placeholder {token}")
        for hit in VOLATILE_QUOTA_RE.finditer(text):
            problems.append(
                f"{where}: hard-coded volatile quota {hit.group(0)!r} — "
                "plan/price/quota figures belong only in "
                "catalog/product-facts.yml (reference facts by id)"
            )

        mirror = MIRROR / skill_dir.name / "SKILL.md"
        if not mirror.is_file():
            problems.append(
                f".claude/skills/{skill_dir.name}/SKILL.md: missing generated "
                "mirror (run scripts/sync_skills.py)"
            )
            continue
        if hashlib.sha256(source.read_bytes()).digest() != hashlib.sha256(
            mirror.read_bytes()
        ).digest():
            problems.append(
                f".claude/skills/{skill_dir.name}/SKILL.md: mirror drift "
                "(run scripts/sync_skills.py)"
            )
        marker = MIRROR / skill_dir.name / MARKER
        if not marker.is_file():
            problems.append(
                f".claude/skills/{skill_dir.name}/{MARKER}: missing generation marker"
            )
        for issue in _mirror_problems(skill_dir, MIRROR / skill_dir.name):
            problems.append(f".claude/skills/{skill_dir.name}: {issue}")

    if len(names) != len(set(names)):
        problems.append("skills: duplicate skill names")
    if set(names) != EXPECTED_SKILLS:
        problems.append(
            f"skills: set mismatch; got {sorted(names)}, expected "
            f"{sorted(EXPECTED_SKILLS)}"
        )

    # No orphan mirror directories left behind by a removed skill.
    if MIRROR.is_dir():
        mirror_names = {p.name for p in MIRROR.iterdir() if p.is_dir()}
        canonical_names = {p.name for p in CANONICAL.iterdir() if p.is_dir()}
        for orphan in sorted(mirror_names - canonical_names):
            problems.append(
                f".claude/skills/{orphan}: mirror has no canonical source "
                "(run scripts/sync_skills.py)"
            )
    problems += _guard_selftest()
    problems += _mirror_selftest()
    return problems


def main() -> int:
    problems = check()
    if problems:
        print("check_skills: FAIL", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print("check_skills: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
