#!/usr/bin/env python3
"""Generate catalog-derived documentation.

The generated files are intentionally small and reviewable. They prove that
`catalog/` is the source of truth for the high-churn matrices while prose docs
remain human-authored.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from _strict_yaml import strict_load

from _workflow_yaml import SELF_WORKFLOWS

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "catalog" / "capabilities.yml"
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"
GENERATED_DIR = REPO_ROOT / "docs" / "generated"
PRODUCT_FACTS = REPO_ROOT / "catalog" / "product-facts.yml"
WORKFLOW_ROUTING = REPO_ROOT / "catalog" / "workflow-routing.yml"
RUNTIME_COVERAGE = REPO_ROOT / "catalog" / "runtime-coverage.yml"


def _load_capabilities() -> list[dict[str, Any]]:
    doc = strict_load(CATALOG)
    return list(doc.get("capabilities", []))


def _load_profiles() -> dict[str, Any]:
    raw = strict_load(REPO_ROOT / "catalog" / "profiles.yml")
    return raw or {}


def _load_product_facts() -> list[dict[str, Any]]:
    doc = strict_load(PRODUCT_FACTS)
    return list(doc.get("facts", []))


def _availability(value: str) -> str:
    return {
        "free": "free",
        "paid": "paid",
        "unavailable": "unavailable",
        "conditional": "conditional",
        "available": "available",
    }.get(value, value)


def _source_verified_through(items: list[dict[str, Any]]) -> str:
    """The newest `last_verified` among the rows a document renders.

    This replaces a hard-coded "Last generated: 2026-07-11" that sat in two
    places and had not moved since July, on documents rendered from a catalog
    edited in August. It said nothing true and nothing checkable — the exact
    shape of claim ADR 0001 exists to prevent, inside the generator that ADR
    points at.

    A wall-clock stamp is not the fix either: it would change on every run and
    make `--check` fail for no reason. The newest source date is deterministic,
    so the drift check stays meaningful, and it answers the question a reader
    actually has — how current is the data underneath this table.
    """
    dates = sorted(
        str(item.get("last_verified"))
        for item in items
        if isinstance(item, dict) and item.get("last_verified")
    )
    return dates[-1] if dates else "unknown"


def capability_matrix(caps: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated capability matrix",
        "",
        "| Capability | Cluster | Status | Public OSS | Private free | Private paid | Workflow | Example |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cap in sorted(caps, key=lambda item: (item["cluster"], item["id"])):
        workflow = cap.get("workflow") or "-"
        example = cap.get("example") or "-"
        lines.append(
            "| {name} (`{id}`) | {cluster} | {status} | {public} | {private_free} | {private_paid} | `{workflow}` | `{example}` |".format(
                name=cap["name"],
                id=cap["id"],
                cluster=cap["cluster"],
                status=cap["status"],
                public=_availability(cap["public_oss"]),
                private_free=_availability(cap["private_free"]),
                private_paid=_availability(cap["private_paid"]),
                workflow=workflow,
                example=example,
            )
        )
    lines.extend([
        "", "---",
        f"Source data verified through: {_source_verified_through(caps)}", "",
    ])
    return "\n".join(lines)


def workflow_inventory(caps: list[dict[str, Any]]) -> str:
    by_workflow: dict[str, list[dict[str, Any]]] = {}
    for cap in caps:
        workflow = cap.get("workflow")
        if workflow:
            by_workflow.setdefault(workflow, []).append(cap)
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated workflow inventory",
        "",
        "| Workflow | Capability IDs | Statuses |",
        "| --- | --- | --- |",
    ]
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        rel = f".github/workflows/{path.name}"
        if path.name in SELF_WORKFLOWS:
            ids = "internal"
            statuses = "internal"
        else:
            caps_for_workflow = by_workflow.get(rel, [])
            ids = ", ".join(f"`{cap['id']}`" for cap in caps_for_workflow) or "MISSING"
            statuses = ", ".join(sorted({cap["status"] for cap in caps_for_workflow})) or "MISSING"
        lines.append(f"| `{rel}` | {ids} | {statuses} |")
    lines.extend([
        "", "---",
        f"Source data verified through: {_source_verified_through(caps)}", "",
    ])
    return "\n".join(lines)


def workflow_routing_matrix() -> str:
    routing = strict_load(WORKFLOW_ROUTING)
    coverage = strict_load(RUNTIME_COVERAGE)
    proven = {
        row.get("workflow"): row.get("proven_os") or []
        for row in coverage.get("entries") or []
        if isinstance(row, dict)
    }
    rows: list[tuple[str, str, list[str], list[str], list[str]]] = []
    for group in routing.get("groups") or []:
        for workflow in group.get("workflows") or []:
            rows.append((workflow, str(group.get("id")),
                         list(group.get("supported_os") or []),
                         list(group.get("runtime_requirements") or []),
                         list(proven.get(workflow) or [])))
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated workflow routing matrix",
        "",
        "`Supported OS` is the fail-closed routing contract. `Runtime-proven OS`",
        "is narrower and records only observed workflow_call evidence; absence",
        "of a value is not proof that a workflow runs on that platform.",
        "",
        "| Workflow | Group | Supported OS | Machine requirements | Runtime-proven OS |",
        "| --- | --- | --- | --- | --- |",
    ]
    for workflow, group, supported, requirements, proven_os in sorted(rows):
        lines.append(
            f"| `{workflow}` | `{group}` | {', '.join(supported)} | "
            f"{', '.join(requirements) or 'shell only'} | {', '.join(proven_os) or '—'} |"
        )
    lines.extend(["", "---", "Generated from catalog/workflow-routing.yml and catalog/runtime-coverage.yml.", ""])
    return "\n".join(lines)


def evidence_orchestration_matrix() -> str:
    contract = strict_load(REPO_ROOT / "catalog" / "evidence-orchestration.yml")
    coverage = strict_load(RUNTIME_COVERAGE)
    coverage_by_workflow = {
        row.get("workflow"): row.get("status") for row in coverage.get("entries") or []
        if isinstance(row, dict)
    }
    evidence = contract["evidence_classes"]
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated evidence orchestration ledger", "",
        "This is a selection contract, not runtime proof. `Observed status` comes",
        "from `runtime-coverage.yml`; host handoffs remain downstream obligations.", "",
        "Timing policy is `observe-only`: duration may be logged but never selects,",
        "skips, cancels, or fails a lane. Evidence classes map downstream to",
        f"operational {evidence['operational']['intended_downstream_retention_days']}d and "
        f"durable {evidence['durable']['intended_downstream_retention_days']}d; this does "
        "not set GitHub artifact retention.", "",
        "| Lane | Minimum level | Platform | OS / arch | Environment | Evidence class | Implementation | Observed status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for lane in contract["lanes"]:
        workflow = lane.get("workflow")
        implementation = f"`{workflow}`" if workflow else f"handoff: {lane['handoff']}"
        observed = coverage_by_workflow.get(workflow, "downstream-unproven") if workflow else "downstream-unproven"
        lines.append(
            f"| `{lane['id']}` | `{lane['minimum_level']}` | {', '.join(lane['platforms'])} | "
            f"{', '.join(lane['operating_systems'])} / {', '.join(lane['architectures'])} | "
            f"`{lane['environment_class']}` | `{lane['evidence_class']}` | {implementation} | `{observed}` |"
        )
    lines.extend(["", "---", "Generated from catalog/evidence-orchestration.yml and catalog/runtime-coverage.yml.", ""])
    return "\n".join(lines)


def runtime_coverage_ledger() -> str:
    coverage = strict_load(RUNTIME_COVERAGE)
    entries = coverage.get("entries") or []
    counts: dict[str, int] = {}
    for row in entries:
        status = str(row.get("status"))
        counts[status] = counts.get(status, 0) + 1
    count_text = ", ".join(f"{key} {counts[key]}" for key in sorted(counts))
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated runtime-evidence closure ledger", "",
        f"Inventory: {len(entries)} reusable workflows ({count_text}).", "",
        "Only `runtime-proven` means an observed successful `workflow_call` run for",
        "the current workflow digest. Every other row is explicit debt; static",
        "validation and skipped jobs are not runtime evidence.", "",
        "| Workflow | Criticality | Status | Risk | Barrier | Required capability | Handoff |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in sorted(entries, key=lambda item: str(item.get("workflow"))):
        debt = row.get("runtime_debt") or {}
        handoff = debt.get("handoff")
        handoff_text = f"[issue]({handoff})" if handoff else "—"
        required = str(debt.get("required_capability", "—")).replace("|", "\\|")
        lines.append(
            f"| `{row['workflow']}` | `{row['criticality']}` | `{row['status']}` | "
            f"`{debt.get('risk', '—')}` | `{debt.get('barrier', '—')}` | "
            f"{required} | {handoff_text} |"
        )
    lines.extend(["", "---", "Generated from catalog/runtime-coverage.yml.", ""])
    return "\n".join(lines)


def scorecard_evidence_ledger() -> str:
    contract = strict_load(REPO_ROOT / "catalog" / "scorecard-evidence.yml")
    consumer = contract["designated_consumer"]
    proof = contract.get("proof")
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated Scorecard SARIF evidence contract", "",
        "This is the only designated public default-branch consumer eligible to",
        "close the Scorecard SARIF runtime obligation. JSON-only, branch, PR,",
        "private, fork, skipped-step, wrong-tool, and wrong-category runs are rejected.", "",
        "| Field | Contract |", "| --- | --- |",
        f"| Repository | `{consumer['repository']}` |",
        f"| Default ref | `refs/heads/{consumer['default_branch']}` |",
        f"| Caller | `{consumer['caller_workflow']}` |",
        f"| Reusable | `{consumer['reusable_workflow']}` |",
        f"| Analysis reusable | `{consumer['analysis_reusable_workflow']}` |",
        f"| Events | {', '.join(consumer['supported_events'])} |",
        f"| Runner | `{consumer['runner']}` |",
        f"| SARIF category / tool | `{consumer['sarif_category']}` / `{consumer['sarif_tool']}` |",
        f"| Scorecard API publish | `{'enabled' if consumer['publish_results'] else 'disabled'}` |",
    ]
    lines.extend([
        "", "## Entrypoint tier and authority matrix", "",
        "| Entrypoint | Public / private tier | Runner | Capability | Permissions | Harden-Runner | Allowed callers | Evidence |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ])
    for row in contract["entrypoint_matrix"]:
        permissions = ", ".join(
            f"{name}:{level}" for name, level in row["permissions"].items()
        )
        harden = row["harden_runner"]
        callers = row["allowed_callers"]
        caller_text = (
            f"{callers['visibility']} {callers['repository_kind']}; "
            f"{','.join(callers['events'])}; {callers['ref']}; {callers['runner']}"
        )
        evidence = ", ".join(row["evidence_obligations"])
        lines.append(
            f"| `{row['workflow']}` | `{row['public_execution_tier']}` / "
            f"`{row['private_execution_tier']}` | `{row['runner_class']}` | "
            f"`{row['capability']}` | `{permissions}` | "
            f"`{harden['pin']}`; `{harden['position']}`; `{harden['egress_policy']}` | "
            f"{caller_text} | {evidence} |"
        )
    attempts = contract.get("attempts") or []
    if attempts:
        attempt = attempts[-1]
        lines.append(
            f"| Preserved failed attempt | `{attempt['attempt']}` / "
            f"`{attempt['classification']}` |"
        )
        if attempt.get("run_url"):
            lines.append(
                f"| Failed run | [run]({attempt['run_url']}) "
                f"(`{attempt['caller_sha']}`) |"
            )
        else:
            lines.append(
                f"| Failure receipt | [issue receipt]({attempt['issue_receipt']}) "
                f"(base `{attempt['base_sha']}`) |"
            )
    if proof:
        lines.extend([
            f"| Runtime status | `accepted` |",
            f"| Caller SHA | `{proof['caller_sha']}` |",
            f"| Run / job | [run]({proof['run_url']}) / [job]({proof['job_url']}) |",
            f"| Analysis ID | `{proof['analysis_id']}` |",
            f"| Reusable digest | `{proof['reusable_digest']}` |",
        ])
    else:
        lines.append("| Runtime status | `pending post-merge default-branch proof` |")
    lines.extend(["", "---", "Generated from catalog/scorecard-evidence.yml.", ""])
    return "\n".join(lines)


def free_tier_matrix(facts: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_docs.py from catalog/product-facts.yml; do not edit by hand. -->",
        "# Generated free-tier / product-fact matrix",
        "",
        "Volatile provider plan and quota facts. Every live row is dated and",
        "expires; `scripts/validate_product_facts.py` fails CI when a live fact is",
        "past its expiry, so a stale tier claim cannot silently mislead adopters.",
        "",
        "| Fact | Provider | Product | Visibility | Plans | Model | Allowance | Status | Verified | Expires |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for fact in sorted(facts, key=lambda f: (str(f.get("provider")), str(f.get("id")))):
        allowance = fact.get("allowance") or {}
        value = allowance.get("value")
        unit = allowance.get("unit", "")
        period = allowance.get("period", "")
        if value is None:
            allowance_text = f"unmetered ({unit})" if period == "unmetered" else (unit or "—")
        else:
            allowance_text = f"{value} {unit}/{period}"
        lines.append(
            "| `{id}` | {provider} | {product} | {vis} | {plans} | {model} | {allowance} | {status} | {verified} | {expires} |".format(
                id=fact.get("id"),
                provider=fact.get("provider"),
                product=fact.get("product"),
                vis=", ".join(fact.get("repository_visibility") or []),
                plans=", ".join(str(p) for p in (fact.get("plans") or [])),
                model=fact.get("model"),
                allowance=allowance_text,
                status=fact.get("status"),
                verified=fact.get("verified_at"),
                expires=fact.get("expires_after") or "—",
            )
        )
    lines.extend(["", "---", "Generated from catalog/product-facts.yml.", ""])
    return "\n".join(lines)


def profile_matrix(doc: dict[str, Any]) -> str:
    import resolve_profile
    caps = _load_capabilities()
    profiles = doc.get("profiles") or []
    matrix = doc.get("entitlement_matrix") or []
    lines = [
        "<!-- Generated by scripts/generate_docs.py from catalog/profiles.yml; do not edit by hand. -->",
        "# Generated operating-profile matrix",
        "",
        "The modes this library supports, as independent axes rather than a",
        "three-tier line. `scripts/validate_profiles.py` enforces that each row is",
        "internally coherent and agrees with the capability and product-fact",
        "catalogs, so prose cannot drift away from it.",
        "",
        "## Profiles",
        "",
        "| Profile | Visibility | Base plan | C/S/Q | Compute billing | Licence billing | CodeQL | Runner | Provenance | Enforcement | Fixed cost | Programme |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for profile in profiles:
        sel = profile.get("selectors") or {}
        ctl = profile.get("controls") or {}
        cost = profile.get("cost") or {}
        fixed = cost.get("fixed_usd")
        lines.append(
            "| `{id}` | {vis} | {plans} | `{mask}` | {compute} | {license} | {codeql} | {runner} | {prov} | {enf} | {cost} | {programme} |".format(
                id=profile.get("id"),
                vis=", ".join(sel.get("visibility") or []),
                plans=", ".join(sel.get("base_plan") or []),
                mask=profile.get("entitlement_mask"),
                compute=ctl.get("compute_billing"),
                license=ctl.get("license_billing"),
                codeql=ctl.get("codeql_mode"),
                runner=ctl.get("runner_mode"),
                prov=ctl.get("release_provenance"),
                enf=ctl.get("enforcement"),
                cost=("free" if not fixed else f"${fixed:g}/month"),
                programme=(lambda r: f"{len(r['included'])} run / {len(r['conditional'])} conditional / {len(r['excluded'])} unavailable")(
                    resolve_profile.resolve(doc, caps, profile)
                ),
            )
        )
    lines.extend(["", "## Entitlement combinations", "",
                  "`mask` is Code Security / Secret Protection / Code Quality.",
                  "Every combination is listed so no repository is unplaceable.", "",
                  "| Mask | C | S | Q | Posture | Free fallbacks |",
                  "| --- | --- | --- | --- | --- | --- |"])
    for row in matrix:
        lines.append(
            "| `{mask}` | {c} | {s} | {q} | {posture} | {fb} |".format(
                mask=row.get("mask"),
                c="on" if row.get("code_security") else "off",
                s="on" if row.get("secret_protection") else "off",
                q="on" if row.get("code_quality") else "off",
                posture=row.get("posture"),
                fb=", ".join(f"`{f}`" for f in (row.get("fallbacks") or [])) or "—",
            )
        )
    for profile in profiles:
        cost = profile.get("cost") or {}
        if not cost.get("fixed_lines"):
            continue
        lines.extend(["", f"## Fixed cost — `{profile.get('id')}`", "",
                      "| Line | Monthly |", "| --- | --- |"])
        total = 0.0
        for item in cost["fixed_lines"]:
            total += float(item.get("usd", 0))
            lines.append(f"| {item.get('line')} | ${float(item.get('usd', 0)):g} |")
        lines.append(f"| **Total** | **${total:g}** |")
        guards = cost.get("guards") or {}
        if guards:
            lines.extend(["", "Guards that make the total a ceiling rather than a hope:", ""])
            for key, value in guards.items():
                lines.append(f"- `{key}: {value}`")
    lines.extend(["", "---", "Generated from catalog/profiles.yml.", ""])
    return "\n".join(lines)


def adr_index() -> str:
    """The decision index, rendered from the ADRs themselves.

    Written as a generated artifact for the same reason ADR 0001 gives: an index
    maintained by hand drifts from the decisions it indexes, silently.
    """
    import re
    adr_dir = REPO_ROOT / "docs" / "adr"
    rows = []
    for path in sorted(adr_dir.glob("[0-9]*.md")):
        text = path.read_text(encoding="utf-8")
        heading = re.match(r"# ADR (\d+): (.+)", text.splitlines()[0])
        status = re.search(r"^Status: (.+)$", text, re.M)
        date = re.search(r"^Date: (.+)$", text, re.M)
        if not (heading and status and date):
            continue
        rows.append((heading.group(1), heading.group(2), status.group(1),
                     date.group(1), path.name))
    lines = [
        "<!-- Generated by scripts/generate_docs.py from docs/adr/*.md; do not edit by hand. -->",
        "",
        "# Architecture decision index",
        "",
        "Decisions that shaped this library, newest first. An ADR records *why* a",
        "contract exists, so a later change reverses it deliberately rather than by",
        "accident. Mechanics live in the catalog and the tier docs; rationale lives here.",
        "",
        "| ADR | Title | Status | Date |",
        "|---|---|---|---|",
    ]
    for num, title, status, date, name in sorted(rows, reverse=True):
        lines.append(f"| [{num}]({name}) | {title} | {status} | {date} |")
    lines.append("")
    return "\n".join(lines)


def render() -> dict[Path, str]:
    caps = _load_capabilities()
    return {
        GENERATED_DIR / "capability-matrix.md": capability_matrix(caps),
        GENERATED_DIR / "workflow-inventory.md": workflow_inventory(caps),
        GENERATED_DIR / "workflow-routing.md": workflow_routing_matrix(),
        GENERATED_DIR / "evidence-orchestration.md": evidence_orchestration_matrix(),
        GENERATED_DIR / "runtime-coverage.md": runtime_coverage_ledger(),
        GENERATED_DIR / "scorecard-evidence.md": scorecard_evidence_ledger(),
        GENERATED_DIR / "free-tier-matrix.md": free_tier_matrix(_load_product_facts()),
        GENERATED_DIR / "profile-matrix.md": profile_matrix(_load_profiles()),
        REPO_ROOT / "docs" / "adr" / "README.md": adr_index(),
    }


def check() -> list[str]:
    stale: list[str] = []
    for path, content in render().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(f"generated doc is stale: {path.relative_to(REPO_ROOT)}")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args()
    outputs = render()
    if args.check:
        stale = check()
        if stale:
            print("generated docs are stale:")
            for path in stale:
                print(f"  - {path}")
            return 1
        print("generate_docs: OK")
        return 0

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
